# Generated by Django 2.0.1 on 2018-02-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=60)),
                ('question', models.CharField(max_length=60)),
                ('recipient', models.CharField(max_length=60)),
                ('sender', models.CharField(max_length=30)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
