# Generated by Django 2.0.1 on 2018-02-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_qnabot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField(max_length=60)),
                ('answer', models.CharField(max_length=60)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
