# Generated by Django 2.0.1 on 2018-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_qnabot', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='qid',
            field=models.IntegerField(),
        ),
    ]
